name: Tharani-pipeline
on: workflow_dispatch
 
jobs:
  My-test-job: 
   runs-on: ubuntu-latest 
   steps:
    - name: Tharani
      run: echo "Tharani"
    - name: install java
      uses: actions/setup-java@v5
      with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '25'
    - name: check java version
      run: java -version
    
     
